### ISSUE TITLE
Why wrap old version of Big.js?

### ISSUE THREAD

**Issue by Bomper** [axetroy/deno_math#6]
The `Big` part just [re-exports an older version of Big.js](https://github.com/axetroy/deno_math/blob/master/big/mod.ts). Big.js recently released a new major version, and this repo is 4 years old.

What's the point of wrapping an old version?

Also [the README](https://github.com/axetroy/deno_math/blob/master/big/README.md) looks unprofessional.

Wouldn't it be better to remove Big.js and let users use it from NPM?

**Comment by axetroy** [comment]
Please note that this repository is 4 years old, when Deno was not mature.

This is for historical reasons.

And the repository is no longer maintained, it is recommended to import Big.js from npm

**Comment by Bomper** [comment]
That makes sense, thanks for clarification. If the repo is no longer maintained, should it be [archived](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)?

I found this repo by googling Deno and arbitrary precision, and npm Big.js didn't even appear in the first 10 search results.
